# Generated by Django 6.0.5 on 2026-06-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_lesson_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_creator',
            new_name='creator',
        ),
    ]
