# Generated by Django 6.0.5 on 2026-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_covers/'),
        ),
    ]
