# Generated by Django 6.0.5 on 2026-06-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='room',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
