# Generated by Django 6.0.5 on 2026-06-08 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_lessonprogress_room_lessonprogress_lesson'),
        ('rooms', '0002_alter_room_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('learner', 'room')},
        ),
    ]
