# Generated by Django 6.0.5 on 2026-06-15 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_lessonprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='comleted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
