# Generated by Django 6.0.5 on 2026-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, default='developing skills'),
            preserve_default=False,
        ),
    ]
