# Generated by Django 6.0.5 on 2026-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak_override',
            field=models.IntegerField(blank=True, help_text='Admin-set streak. When set, overrides the calculated streak.', null=True),
        ),
    ]
