# Generated by Django 6.0.5 on 2026-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
